package kingbase

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
)

type oracleTypeModel struct {
	ID        uint    `gorm:"primary_key"`
	Name      string  `gorm:"size:64;not null"`
	Note      string  `gorm:"comment:'long text'"`
	Price     float64 `gorm:"type:decimal(10,2);not null"`
	Payload   []byte
	Active    bool `gorm:"not null;default:true"`
	CreatedAt time.Time
}

type oracleInsertModel struct {
	ID   uint `gorm:"primary_key"`
	Name string
}

type oracleForeignKeyParent struct {
	ID uint `gorm:"primary_key"`
}

type oracleForeignKeyChild struct {
	ID       uint `gorm:"primary_key"`
	ParentID uint `gorm:"not null"`
	Parent   oracleForeignKeyParent
}

type mysqlTypeModel struct {
	ID      uint   `gorm:"primary_key"`
	Name    string `gorm:"size:64;not null"`
	Note    string
	Payload []byte
	Amount  uint64
}

func openMockGorm(t *testing.T, dialect string) (*gorm.DB, sqlmock.Sqlmock, func()) {
	t.Helper()
	sqlDB, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("create sqlmock: %v", err)
	}
	db, err := gorm.Open(dialect, sqlDB)
	if err != nil {
		_ = sqlDB.Close()
		t.Fatalf("open gorm: %v", err)
	}
	return db, mock, func() {
		_ = db.Close()
	}
}

func fieldType(t *testing.T, db *gorm.DB, model interface{}, name string) string {
	t.Helper()
	for _, field := range db.NewScope(model).GetModelStruct().StructFields {
		if field.Name == name {
			return strings.ToLower(db.Dialect().DataTypeOf(field))
		}
	}
	t.Fatalf("field %s not found", name)
	return ""
}

func TestKingbaseOracleTypeMapping(t *testing.T) {
	db, _, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	assertType := func(field, want string) {
		t.Helper()
		if got := fieldType(t, db, &oracleTypeModel{}, field); got != strings.ToLower(want) {
			t.Fatalf("%s type mismatch: got %q, want %q", field, got, want)
		}
	}

	assertType("ID", "integer generated by default as identity")
	assertType("Name", "varchar2(64) NOT NULL")
	assertType("Note", "clob")
	assertType("Price", "number(10,2) NOT NULL")
	assertType("Payload", "blob")
	assertType("Active", "boolean NOT NULL DEFAULT true")
	assertType("CreatedAt", "timestamp with time zone")
}

func TestKingbaseOracleForeignKeyUsesIdentityBaseType(t *testing.T) {
	db, _, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	if got, want := fieldType(t, db, &oracleForeignKeyChild{}, "ParentID"), "integer NOT NULL"; got != strings.ToLower(want) {
		t.Fatalf("foreign key type mismatch: got %q, want %q", got, strings.ToLower(want))
	}
}

func TestKingbaseMySQLTypeMapping(t *testing.T) {
	db, _, cleanup := openMockGorm(t, DialectKingbaseMySQL)
	defer cleanup()

	assertType := func(field, want string) {
		t.Helper()
		if got := fieldType(t, db, &mysqlTypeModel{}, field); got != strings.ToLower(want) {
			t.Fatalf("%s type mismatch: got %q, want %q", field, got, want)
		}
	}

	assertType("ID", "serial")
	assertType("Name", "varchar(64) NOT NULL")
	assertType("Note", "varchar(255)")
	assertType("Payload", "varbinary(255)")
	assertType("Amount", "numeric(20,0)")
}

func TestKingbaseRawDialectIsConnectionScoped(t *testing.T) {
	db1, _, cleanup1 := openMockGorm(t, DialectKingbaseMySQL)
	defer cleanup1()
	db2, _, cleanup2 := openMockGorm(t, DialectKingbaseMySQL)
	defer cleanup2()

	dialect1, ok := db1.Dialect().(*kingbaseMySQLDialect)
	if !ok {
		t.Fatalf("unexpected first dialect type: %T", db1.Dialect())
	}
	dialect2, ok := db2.Dialect().(*kingbaseMySQLDialect)
	if !ok {
		t.Fatalf("unexpected second dialect type: %T", db2.Dialect())
	}
	if dialect1.raw == nil || dialect2.raw == nil {
		t.Fatal("raw dialect was not initialized")
	}
	if dialect1.raw == dialect2.raw {
		t.Fatal("raw dialect instances are shared between connections")
	}
}

func TestNewKingbaseDialectInitializesMode(t *testing.T) {
	tests := []struct {
		mode KbMode
		want string
	}{
		{mode: KbModeMySQL, want: DialectKingbaseMySQL},
		{mode: KbModeOracle, want: DialectKingbaseOracle},
	}
	for _, tt := range tests {
		if got := NewKingbaseDialect(tt.mode).GetName(); got != tt.want {
			t.Errorf("mode %q returned dialect %q, want %q", tt.mode, got, tt.want)
		}
	}
}

func TestNewKingbaseDialectRejectsUnsupportedMode(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("unsupported mode should panic")
		}
	}()

	NewKingbaseDialect(KbMode("unsupported"))
}

func TestKingbaseOracleDialectIsSelfContained(t *testing.T) {
	dialect, ok := NewKingbaseDialect(KbModeOracle).(*kingbaseOracleDialect)
	if !ok {
		t.Fatalf("unexpected oracle dialect type: %T", NewKingbaseDialect(KbModeOracle))
	}

	if got := dialect.GetName(); got != DialectKingbaseOracle {
		t.Fatalf("dialect name mismatch: got %q, want %q", got, DialectKingbaseOracle)
	}
	if got := dialect.BindVar(1); got != "?" {
		t.Fatalf("bind variable mismatch: got %q, want %q", got, "?")
	}
	if got := dialect.SelectFromDummyTable(); got != "FROM DUAL" {
		t.Fatalf("dummy table mismatch: got %q", got)
	}
	if got := dialect.LastInsertIDOutputInterstitial("users", "id", []string{"name"}); got != "" {
		t.Fatalf("unexpected output interstitial: %q", got)
	}
	if got, want := dialect.LastInsertIDReturningSuffix(`"users"`, `"id"`), `RETURNING "users"."id"`; got != want {
		t.Fatalf("returning suffix mismatch: got %q, want %q", got, want)
	}
	if got := dialect.DefaultValueStr(); got != "DEFAULT VALUES" {
		t.Fatalf("default value SQL mismatch: got %q", got)
	}
	if got, want := dialect.BuildKeyName("idx", "users", "name"), "idx_users_name"; got != want {
		t.Fatalf("key name mismatch: got %q, want %q", got, want)
	}
	if index, column := dialect.NormalizeIndexAndColumn("idx_users_name", "name"); index != "idx_users_name" || column != "name" {
		t.Fatalf("normalized index mismatch: index=%q column=%q", index, column)
	}
	if dialect.CurrentDatabase() != "" {
		t.Fatal("dialect without DB returned a current schema")
	}
	if dialect.HasTable("users") || dialect.HasColumn("users", "name") ||
		dialect.HasIndex("users", "idx_users_name") || dialect.HasForeignKey("users", "fk_users_company") {
		t.Fatal("metadata lookup without DB unexpectedly succeeded")
	}
	if err := dialect.RemoveIndex("users", "idx_users_name"); err != sql.ErrConnDone {
		t.Fatalf("expected sql.ErrConnDone without DB, got %v", err)
	}
}

func TestKingbaseOracleCurrentSchemaAndRemoveIndex(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	mock.ExpectQuery(regexp.QuoteMeta("SELECT current_schema()")).
		WillReturnRows(sqlmock.NewRows([]string{"current_schema"}).AddRow("APP"))
	if got := db.Dialect().CurrentDatabase(); got != "APP" {
		t.Fatalf("current schema mismatch: got %q, want %q", got, "APP")
	}

	mock.ExpectExec(regexp.QuoteMeta("DROP INDEX APP.idx_users_name")).
		WillReturnResult(sqlmock.NewResult(0, 0))
	if err := db.Dialect().RemoveIndex("APP.users", "idx_users_name"); err != nil {
		t.Fatalf("RemoveIndex returned error: %v", err)
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}
}

func TestKingbaseOracleCreateUsesGokbBindingAndReturning(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	mock.ExpectBegin()
	mock.ExpectQuery(regexp.QuoteMeta(`INSERT INTO "users" ("name") VALUES (?) RETURNING "users"."id"`)).
		WithArgs("alice").
		WillReturnRows(sqlmock.NewRows([]string{"id"}).AddRow(42))
	mock.ExpectCommit()

	user := oracleInsertModel{Name: "alice"}
	if err := db.Table("users").Create(&user).Error; err != nil {
		t.Fatalf("Create returned error: %v", err)
	}
	if user.ID != 42 {
		t.Fatalf("primary key mismatch: got %d, want 42", user.ID)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}
}

func TestKingbaseOraclePagination(t *testing.T) {
	db, _, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	tests := []struct {
		name   string
		limit  interface{}
		offset interface{}
		want   string
	}{
		{name: "limit", limit: 10, want: " FETCH FIRST 10 ROWS ONLY"},
		{name: "limit and offset", limit: "10", offset: 20, want: " OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY"},
		{name: "offset", offset: 20, want: " OFFSET 20 ROWS"},
		{name: "negative values", limit: -1, offset: -1, want: ""},
		{name: "unset", want: ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := db.Dialect().LimitAndOffsetSQL(tt.limit, tt.offset)
			if err != nil {
				t.Fatalf("LimitAndOffsetSQL returned error: %v", err)
			}
			if got != tt.want {
				t.Fatalf("pagination mismatch: got %q, want %q", got, tt.want)
			}
		})
	}

	if _, err := db.Dialect().LimitAndOffsetSQL("invalid", nil); err == nil {
		t.Fatal("expected invalid limit to return an error")
	}
	if _, err := db.Dialect().LimitAndOffsetSQL(nil, "invalid"); err == nil {
		t.Fatal("expected invalid offset to return an error")
	}
}

func TestKingbaseOracleModifyColumnQuotesIdentifiers(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	mock.ExpectExec(regexp.QuoteMeta(`ALTER TABLE "APP"."Order" MODIFY "select" varchar2(128)`)).
		WillReturnResult(sqlmock.NewResult(0, 0))
	if err := db.Table(`APP.Order`).ModifyColumn("select", "varchar2(128)").Error; err != nil {
		t.Fatalf("ModifyColumn returned error: %v", err)
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}

	dialect := &kingbaseOracleDialect{}
	if err := dialect.ModifyColumn("users", "name", "varchar2(64)"); err != sql.ErrConnDone {
		t.Fatalf("expected sql.ErrConnDone without DB, got %v", err)
	}
}

func TestKingbaseOracleQuoteEscapesIdentifier(t *testing.T) {
	dialect := &kingbaseOracleDialect{}
	if got, want := dialect.Quote(`order"detail`), `"order""detail"`; got != want {
		t.Fatalf("quoted identifier mismatch: got %q, want %q", got, want)
	}
	if got, want := quoteOracleIdentifierPath(`"APP"."Order"`), `"APP"."Order"`; got != want {
		t.Fatalf("quoted path mismatch: got %q, want %q", got, want)
	}
}

func TestKingbaseOracleMetadataSQL(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	expectCount := func(query string, args ...driver.Value) {
		t.Helper()
		mock.ExpectQuery(regexp.QuoteMeta(query)).
			WithArgs(args...).
			WillReturnRows(sqlmock.NewRows([]string{"count"}).AddRow(1))
	}

	expectCount("SELECT COUNT(*) FROM user_tables WHERE LOWER(table_name) = LOWER(?)", "users")
	if !db.Dialect().HasTable("users") {
		t.Fatal("expected oracle HasTable to use user_tables")
	}

	expectCount("SELECT COUNT(*) FROM user_tab_columns WHERE LOWER(table_name) = LOWER(?) AND LOWER(column_name) = LOWER(?)", "users", "name")
	if !db.Dialect().HasColumn("users", "name") {
		t.Fatal("expected oracle HasColumn to use user_tab_columns")
	}

	expectCount("SELECT COUNT(*) FROM user_indexes WHERE LOWER(table_name) = LOWER(?) AND LOWER(index_name) = LOWER(?)", "users", "idx_users_name")
	if !db.Dialect().HasIndex("users", "idx_users_name") {
		t.Fatal("expected oracle HasIndex to use user_indexes")
	}

	expectCount("SELECT COUNT(*) FROM user_constraints WHERE LOWER(table_name) = LOWER(?) AND LOWER(constraint_name) = LOWER(?) AND constraint_type = 'R'", "users", "fk_users_company")
	if !db.Dialect().HasForeignKey("users", "fk_users_company") {
		t.Fatal("expected oracle HasForeignKey to use user_constraints")
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}
}

func TestKingbaseOracleMetadataSQLWithSchema(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	expectCount := func(query string, args ...driver.Value) {
		t.Helper()
		mock.ExpectQuery(regexp.QuoteMeta(query)).
			WithArgs(args...).
			WillReturnRows(sqlmock.NewRows([]string{"count"}).AddRow(1))
	}

	expectCount("SELECT COUNT(*) FROM all_tables WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?)", "APP", "users")
	if !db.Dialect().HasTable(`"APP"."users"`) {
		t.Fatal("expected schema-qualified HasTable to use all_tables")
	}
	expectCount("SELECT COUNT(*) FROM all_tab_columns WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(column_name) = LOWER(?)", "APP", "users", "name")
	if !db.Dialect().HasColumn(`"APP"."users"`, `"name"`) {
		t.Fatal("expected schema-qualified HasColumn to use all_tab_columns")
	}
	expectCount("SELECT COUNT(*) FROM all_indexes WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(index_name) = LOWER(?)", "APP", "users", "idx_users_name")
	if !db.Dialect().HasIndex(`"APP"."users"`, `"idx_users_name"`) {
		t.Fatal("expected schema-qualified HasIndex to use all_indexes")
	}
	expectCount("SELECT COUNT(*) FROM all_constraints WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(constraint_name) = LOWER(?) AND constraint_type = 'R'", "APP", "users", "fk_users_company")
	if !db.Dialect().HasForeignKey(`"APP"."users"`, `"fk_users_company"`) {
		t.Fatal("expected schema-qualified HasForeignKey to use all_constraints")
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}
}

func TestKingbaseOracleMetadataFallsBackToInformationSchema(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	mock.ExpectQuery(regexp.QuoteMeta("SELECT COUNT(*) FROM user_tables WHERE LOWER(table_name) = LOWER(?)")).
		WithArgs("users").
		WillReturnError(fmt.Errorf("oracle catalog is unavailable"))
	mock.ExpectQuery(regexp.QuoteMeta("SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_schema) = LOWER(current_schema()) AND LOWER(table_name) = LOWER(?)")).
		WithArgs("users").
		WillReturnRows(sqlmock.NewRows([]string{"count"}).AddRow(1))

	if !db.Dialect().HasTable("users") {
		t.Fatal("expected HasTable to fall back to information_schema")
	}
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}
}

func TestKingbaseOracleSchemaMetadataFallsBackWhenOracleCatalogIsEmpty(t *testing.T) {
	db, mock, cleanup := openMockGorm(t, DialectKingbaseOracle)
	defer cleanup()

	expectZero := func(query string, args ...driver.Value) {
		t.Helper()
		mock.ExpectQuery(regexp.QuoteMeta(query)).
			WithArgs(args...).
			WillReturnRows(sqlmock.NewRows([]string{"count"}).AddRow(0))
	}
	expectOne := func(query string, args ...driver.Value) {
		t.Helper()
		mock.ExpectQuery(regexp.QuoteMeta(query)).
			WithArgs(args...).
			WillReturnRows(sqlmock.NewRows([]string{"count"}).AddRow(1))
	}

	expectZero("SELECT COUNT(*) FROM all_tables WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?)", "public", "users")
	expectOne("SELECT COUNT(*) FROM information_schema.tables WHERE LOWER(table_schema) = LOWER(?) AND LOWER(table_name) = LOWER(?)", "public", "users")
	if !db.Dialect().HasTable("public.users") {
		t.Fatal("expected schema-qualified HasTable to fall back when all_tables is empty")
	}

	expectZero("SELECT COUNT(*) FROM all_tab_columns WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(column_name) = LOWER(?)", "public", "users", "name")
	expectOne("SELECT COUNT(*) FROM information_schema.columns WHERE LOWER(table_schema) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(column_name) = LOWER(?)", "public", "users", "name")
	if !db.Dialect().HasColumn("public.users", "name") {
		t.Fatal("expected schema-qualified HasColumn to fall back when all_tab_columns is empty")
	}

	expectZero("SELECT COUNT(*) FROM all_indexes WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(index_name) = LOWER(?)", "public", "users", "idx_users_name")
	expectOne("SELECT COUNT(*) FROM pg_indexes WHERE LOWER(schemaname) = LOWER(?) AND LOWER(tablename) = LOWER(?) AND LOWER(indexname) = LOWER(?)", "public", "users", "idx_users_name")
	if !db.Dialect().HasIndex("public.users", "idx_users_name") {
		t.Fatal("expected schema-qualified HasIndex to fall back when all_indexes is empty")
	}

	expectZero("SELECT COUNT(*) FROM all_constraints WHERE LOWER(owner) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(constraint_name) = LOWER(?) AND constraint_type = 'R'", "public", "users", "fk_users_company")
	expectOne("SELECT COUNT(*) FROM information_schema.table_constraints WHERE LOWER(table_schema) = LOWER(?) AND LOWER(table_name) = LOWER(?) AND LOWER(constraint_name) = LOWER(?) AND constraint_type = 'FOREIGN KEY'", "public", "users", "fk_users_company")
	if !db.Dialect().HasForeignKey("public.users", "fk_users_company") {
		t.Fatal("expected schema-qualified HasForeignKey to fall back when all_constraints is empty")
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("sql expectations: %v", err)
	}
}
